config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "products#index"

  resources :products do
    collection do
      get :import
      post :batch_create
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
# frozen_string_literal: true

require 'csv'

class ProductsController < ApplicationController
  before_action :set_file_product, only: :batch_create
  before_action :check_file, only: :batch_create

  def index; end

  def import; end

  def batch_create
    products = Array.new()
    errors = Array.new()

    file = File.open(@file_product)
    csv = CSV.parse(file, headers: true)

    csv.each_with_index do |row, index|
      begin
        next errors << {row: index + 1, error: "Data at row #{index+1} is empty."} if row[0].nil?
        
        products << { name: row[0], sku: row[2], price: row[1] }
      rescue StandardError => error
        redirect_to products_path, alert: "Import failed: #{error.message}"
      end
    end

    Product.insert_all!(products)
    
    redirect_to root_path
  end

  private

  # Prevent file is empty or not csv
  def check_file
    redirect_to import_products_path if @file_product.nil? || @file_product.content_type != 'text/csv'
  end

  def set_file_product
    @file_product = params[:file_product]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImportRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/import.html.erb
<h1>Import Products</h1>

<%= form_tag batch_create_products_path, method: :post, multipart: true do %>
  <div class="field">
    <%= label_tag :file_product, "Product CSV File" %>
    <%= file_field_tag :file_product %>
  </div>

  <div class="actions">
    <%= submit_tag "Import Products" %>
  </div>
<% end %>

app/views/products/index.html.erb
<h1>Index</h1>